import React from "react";
import type { Metadata } from "next";
import { Header, Footer, Sidebar, BackToTop } from "@/components/layouts";
import AuthProvider from "@/context/authContext";

export const metadata: Metadata = {
  title: "Main Layout",
  description: "Generated by create next app",
};

export default function MainLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <React.Fragment>
      <AuthProvider>
        <div className="page">
          <Header />
          {/* <Sidebar /> */}
          <div className="content">
            <div className="main-content">{children}11</div>
          </div>
          <Footer />
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        ss
        <BackToTop />
      </AuthProvider>
    </React.Fragment>
  );
}
